import '@/styles/globals.css';
import type { Metadata } from 'next'
import UserProvider from "@/providers/UserProvider";
import ToastProvider from '@/providers/ToastProvider';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'QuizyMe | Auth',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="container mx-auto min-h-screen bg-gray-50">
        <Link
          type="button"
          className="fixed top-2 right-2 px-8 py-1 bg-black rounded-full ring-2 ring-black text-white font-bold hover:bg-white hover:text-black duration-300"
          href="/"
        >
          Home
        </Link>
        <UserProvider>
          <ToastProvider>
            {children}
          </ToastProvider>
        </UserProvider>
      </body>
    </html>
  )
}