import '@/styles/globals.css';
import type { Metadata } from 'next'
import UserProvider from "@/providers/UserProvider";
import ToastProvider from '@/providers/ToastProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="container mx-auto min-h-screen bg-gray-50">
        <UserProvider>
          <ToastProvider>
            {children}
          </ToastProvider>
        </UserProvider>
      </body>
    </html>
  )
}