import type { Metadata } from 'next';
import '@/styles/globals.css';
import Navbar from '@/components/Navbar/Navbar';
import Footer from '@/components/Footer/Footer';
import UserProvider from '@/providers/UserProvider';

export const metadata: Metadata = {
  title: 'QuizyMe',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <Navbar />
          <div className='container mx-auto pt-28 min-h-screen'>
            {children}
          </div>
          <Footer />
        </body>
      </UserProvider>
    </html>
  )
}
